apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80              # External service port
      targetPort: 5000      # Flask container port
      nodePort: 30000       # Fixed port on Minikube
  type: NodePort            # Correct type for Minikube with a fixed port
